/* Felix Capabilities Guide — single source of truth.
   Capabilities only. No client data. Edit here; both pages read from window.FELIX. */
window.FELIX = {
  categories: [
    { id:"cadence",      name:"Daily & Weekly Cadence",        desc:"The rhythm commands — how Felix keeps the practice oriented day to day and week to week." },
    { id:"recordings",   name:"Recordings → Memos",            desc:"Turning voice recordings and ambient capture into filed memos-to-file, automatically de-duplicated across devices." },
    { id:"billing",      name:"Time & Billing",                desc:"Capturing billable work from across the practice, proposing entries, and recovering work that slipped through." },
    { id:"cases",        name:"Case & Matter Management",      desc:"Opening matters, checking conflicts, briefing status, and preparing for and processing meetings." },
    { id:"drafting",     name:"Drafting & Communications",     desc:"Producing correspondence and client-ready drafts — always reviewed before anything goes out." },
    { id:"filings",      name:"Filings & Court",               desc:"Reading incoming court paper and driving Connecticut probate e-filing and document retrieval." },
    { id:"research",     name:"Legal Research",                desc:"Connecticut and federal legal authority — statutes, regulations, case law, Medicaid policy, and fair hearings — plus the probate practice library, death verification, and land-records research." },
    { id:"elderlaw",     name:"Elder Law Skills",              desc:"Connecticut-specific substantive knowledge Felix applies when working a probate, Medicaid, or planning matter." },
    { id:"slash",        name:"Guided Commands (/elder-law)",  desc:"Step-by-step interactive workflows for the most involved elder-law tasks." },
    { id:"automation",   name:"Always-On Automation",          desc:"Background daemons that watch, triage, and file without being asked — plus the status dashboard that monitors them." },
    { id:"integrations", name:"Connected Systems",             desc:"The external services Felix reads from and writes to. Each is integrated narrowly, returning only what a task needs." },
  ],

  items: [
    /* ---------------- Cadence ---------------- */
    { id:"check-in", cat:"cadence", kind:"command", name:"Check In",
      trigger:"Check In", command:"Check In", invoke:"Say this to Felix",
      blurb:"A tight snapshot of where things stand — today and yesterday only — across calendar, conversations, tasks, email, and notes.",
      detail:"Check In is the fastest way to reorient at the start of a work block. It pulls a deliberately narrow slice — today and yesterday only — and stops at roughly fifteen items so it stays a glance rather than a report.",
      steps:["Calendar events for today","Recent conversation transcripts (last few days)","Top tasks from the task manager","Email from the last couple of business days","Knowledge-base notes for today and yesterday"],
      notes:["Scoped to today + yesterday on purpose — no future dates and no deadline calendar, so it never balloons.","Results are cached briefly, so a follow-up “Bill this” can reuse them without re-scanning."],
      related:["deadlines","weekly-review","bill"] },

    { id:"deadlines", cat:"cadence", kind:"command", name:"Deadlines",
      trigger:"Deadlines", command:"Deadlines", invoke:"Say this to Felix",
      blurb:"Upcoming court dates, filing deadlines, and due tasks for the next 30 days, color-coded by urgency.",
      detail:"Deadlines answers “what's coming up?” It reads the due-dates calendar and the task manager, then sorts everything by how soon it's due — putting court, filing, and client commitments at the top.",
      steps:["Reads the due-dates calendar for the next 30 days","Reads due tasks from the task manager","Groups by urgency: overdue, today, tomorrow, this week, next week, later","Surfaces court and filing items first"],
      examples:["Check deadlines","What's due this week?"],
      related:["check-in","weekly-review","case-briefing"] },

    { id:"weekly-review", cat:"cadence", kind:"command", name:"Weekly Review",
      trigger:"Weekly review", command:"Weekly review", invoke:"Say this to Felix",
      blurb:"A Monday-through-Friday roll-up of the week's work across the practice.",
      detail:"Weekly Review steps back from the day-to-day and summarizes the week — what moved, what's outstanding, and where attention is needed. Defaults to the current Monday–Friday range.",
      examples:["Week in review","Weekly review for last week"],
      related:["check-in","deadlines"] },

    /* ---------------- Recordings ---------------- */
    { id:"plaud-sync", cat:"recordings", kind:"command", name:"Plaud Sync",
      trigger:"Sync Plaud", command:"Sync Plaud", invoke:"Say this to Felix",
      blurb:"Pulls new voice recordings, transcribes them, and drafts a memo-to-file for each in the attorney's voice.",
      detail:"Plaud Sync takes recorded conversations and turns each into a finished memo-to-file — written in the first person from the attorney's point of view, as narrative paragraphs rather than a raw transcript. Memos with follow-up items also generate the matching tasks.",
      steps:["Fetches recordings not yet processed","Transcribes and identifies the conversation","Drafts a memo-to-file in the firm's memo format","Files it to the knowledge base and creates any follow-up tasks"],
      examples:["Process recordings","Sync Plaud for yesterday"],
      notes:["Recording titles are not always reliable — Felix verifies names against the case file before drafting."],
      related:["omi-desktop-sync","sweep","post-meeting"] },

    { id:"omi-desktop-sync", cat:"recordings", kind:"command", name:"Omi Desktop Sync",
      trigger:"Sync Omi Desktop", command:"Sync Omi Desktop", invoke:"Say this to Felix",
      blurb:"The same recording-to-memo pipeline for desktop ambient-capture sessions.",
      detail:"Omi Desktop Sync mirrors Plaud Sync for conversations captured at the desk — transcribing each session and drafting a memo-to-file for review.",
      examples:["Process Omi Desktop","Sync Omi Desktop for [date]"],
      related:["plaud-sync","sweep"] },

    { id:"sweep", cat:"recordings", kind:"command", name:"Sweep",
      trigger:"Sweep [date]", command:"Sweep", invoke:"Say this to Felix",
      blurb:"A cross-source pass that unifies recordings captured by multiple devices for the same day, removes overlaps, and files one clean memo per conversation.",
      detail:"When the same conversation is captured by more than one device, Sweep reconciles them — picking the best source, removing duplicates, and filing a single memo per real conversation so the record isn't cluttered with near-copies.",
      examples:["Sweep today","Sweep [date]"],
      related:["plaud-sync","omi-desktop-sync"] },

    /* ---------------- Billing ---------------- */
    { id:"bill", cat:"billing", kind:"command", name:"Bill",
      trigger:"Bill today", command:"Bill today", invoke:"Say this to Felix",
      blurb:"Turns a single day's work into proposed time entries at the firm's rate and increment, ready to confirm.",
      detail:"Bill takes one day and proposes time entries from the day's activity. It rounds to the firm's billing increment and uses the standard rate unless the matter has its own. Nothing posts until you confirm the client for each entry.",
      examples:["Bill today","Bill [date]","Bill this"],
      notes:["Felix never guesses the client — it asks you to confirm the client name as it appears in billing.","Time is billed at actual clock time and rounded down to the increment."],
      related:["scan-billing","review-billing","billing-recovery","check-in"] },

    { id:"scan-billing", cat:"billing", kind:"command", name:"Scan for Billing",
      trigger:"Scan for billing [range]", command:"Scan for billing this week", invoke:"Say this to Felix",
      blurb:"Scans recent activity across recordings, calendar, email, and notes for work that hasn't been billed, with duplicates removed.",
      detail:"Scan for Billing sweeps recent activity for billable work that hasn't yet been entered, de-duplicating overlapping evidence from different sources. It then chains into Review Billing so you can vet the proposed entries.",
      steps:["Gathers candidate work from recordings, calendar, email, and notes","De-duplicates overlapping items by source priority","Presents each candidate and asks for the client","Hands off to Review Billing"],
      examples:["Scan for billing yesterday","Scan billable work this week"],
      related:["review-billing","bill","billing-recovery"] },

    { id:"review-billing", cat:"billing", kind:"command", name:"Review Billing",
      trigger:"Review billing", command:"Review billing", invoke:"Say this to Felix",
      blurb:"Walks proposed entries for accuracy and client attribution before any of them post.",
      detail:"Review Billing is the checkpoint between a scan and the billing system — it presents proposed entries for confirmation, correction, or deletion before anything is written.",
      related:["scan-billing","bill"] },

    { id:"billing-recovery", cat:"billing", kind:"command", name:"Billing Recovery",
      trigger:"Recover billing [range]", command:"Recover billing [range]", invoke:"Say this to Felix",
      blurb:"An exhaustive historical sweep that hunts for work that was done but never captured.",
      detail:"Where Scan for Billing looks at recent unbilled work, Billing Recovery is the deep historical pass — searching every source by every party name to find work that was performed but never entered, then verifying against the billing system so nothing is double-counted.",
      examples:["Recover billing [range]","Find unbilled work [range]"],
      notes:["Designed to be exhaustive across sources — it verifies against existing entries to avoid duplicates."],
      related:["scan-billing","bill"] },

    /* ---------------- Cases ---------------- */
    { id:"client-lookup", cat:"cases", kind:"command", name:"Client Lookup",
      trigger:"Lookup [client name]", command:"Lookup [client name]", invoke:"Say this to Felix",
      blurb:"Pulls a client together from five sources at once — billing, contacts, recent notes, the email archive, and recent inbox.",
      detail:"Client Lookup assembles a single picture of a client by querying billing/matters, contact details, recent knowledge-base notes, the historical email archive, and the recent inbox — then offers next actions like emailing, calling, or starting a billing entry.",
      examples:["Lookup [name]","Find client [name]"],
      related:["case-briefing","conflict-check","new-case"] },

    { id:"new-case", cat:"cases", kind:"command", name:"New Case",
      trigger:"New case", command:"New case", invoke:"Say this to Felix",
      blurb:"Guided setup for a new matter, keeping client, matter, and folder distinct — with a conflict check before anything is created.",
      detail:"New Case walks through opening a matter, holding the distinction between the client (the person represented), the matter (the estate, trust, or proceeding), and the folder (named for the subject). A conflict check runs automatically and blocks the setup on a hard conflict until it's resolved.",
      steps:["Gathers client, matter, and folder details","Runs a conflict check — blocks on a hard hit","Creates the matter and folder structure","Records the matter in the billing system"],
      notes:["A hard conflict halts the process until you decide how to proceed."],
      related:["conflict-check","case-activation","client-lookup","slash-case-intake"] },

    { id:"conflict-check", cat:"cases", kind:"command", name:"Conflict Check",
      trigger:"Conflict check [names]", command:"Conflict check [names]", invoke:"Say this to Felix",
      blurb:"Checks proposed parties against every prior client and matter plus the email archive, and flags hard conflicts before work begins.",
      detail:"Conflict Check runs proposed parties against the full client and matter history — using exact, phonetic, and fuzzy matching plus one degree of relationship expansion — and searches the historical email archive. It records a disposition for each check so the firm has an audit trail.",
      steps:["Matches names against the conflicts database (exact + phonetic + fuzzy)","Expands to related parties one degree out","Searches the historical email archive","Returns CLEAR, SOFT, or HARD and logs the disposition"],
      notes:["Runs automatically inside New Case and Case Intake, where a hard hit is blocking."],
      related:["new-case","slash-conflict-check","mailsteward"] },

    { id:"case-activation", cat:"cases", kind:"command", name:"Case Activation",
      trigger:"(provide a matter folder)", command:"Activate the case at [folder path]", invoke:"Give Felix the matter folder",
      blurb:"Activates a matter for focused work, with a mandatory court-status check and a confirmation step.",
      detail:"Point Felix at a matter folder and it loads the matter for focused work — running a mandatory court-status check first, defaulting court searches to non-confidential, and asking before it creates any saved case state.",
      notes:["Court status is always checked on activation.","Felix asks before creating case state — it won't assume."],
      related:["case-briefing","client-lookup"] },

    { id:"case-briefing", cat:"cases", kind:"command", name:"Case Briefing",
      trigger:"Status on [case]", command:"Status on [case]", invoke:"Say this to Felix",
      blurb:"Current status, open tasks, and the next deadline for a matter — with a quick mode for just the critical items.",
      detail:"Case Briefing pulls a matter's current posture together: where things stand, what's open, and what's due next. Ask for a “quick status” to get only the critical items, open tasks, and next deadline.",
      examples:["Brief me on [case]","Where are we on [case]","Quick status on [case]"],
      related:["case-activation","deadlines","meeting-prep"] },

    { id:"meeting-prep", cat:"cases", kind:"command", name:"Meeting Prep",
      trigger:"Prep for [client] meeting", command:"Prep for [client] meeting", invoke:"Say this to Felix",
      blurb:"Assembles background, a summary of recent interactions, and an agenda ahead of a client meeting.",
      detail:"Meeting Prep gets you ready for a conversation — recent interactions, the matter's open items, relevant background, and a suggested agenda. Especially useful before a difficult conversation, where it adds focused research and a draft.",
      examples:["Meeting prep [client]"],
      related:["post-meeting","case-briefing","client-lookup"] },

    { id:"post-meeting", cat:"cases", kind:"command", name:"Post-Meeting Processing",
      trigger:"Process [client] meeting", command:"Process [client] meeting", invoke:"Say this to Felix",
      blurb:"Turns a meeting recording into a filed memo and a set of follow-up tasks.",
      detail:"After a meeting, this takes the recording (preferring the highest-quality source available), drafts a memo-to-file, and creates the follow-up tasks the memo identifies.",
      examples:["Post-meeting [client]","Wrap up [client] meeting"],
      related:["meeting-prep","plaud-sync"] },

    /* ---------------- Drafting ---------------- */
    { id:"cover-letter", cat:"drafting", kind:"command", name:"Cover Letter",
      trigger:"Cover letter for [filing]", command:"Cover letter for [filing or matter]", invoke:"Say this to Felix",
      blurb:"Drafts a transmittal or cover letter for a filing or mailing, on firm letterhead and to firm standards.",
      detail:"Cover Letter produces a transmittal letter for a filing or mailing — to the court or a third party — on firm letterhead and in the firm's voice. As with all outgoing material, it's presented for review and never sent on its own.",
      examples:["Draft cover letter to [court/party]"],
      notes:["Drafts only — nothing is sent without an explicit instruction to send."],
      related:["email-reply","document-drafting"] },

    { id:"email-reply", cat:"drafting", kind:"command", name:"Email Reply with Context",
      trigger:"Reply to [client] email", command:"Reply to [client] email", invoke:"Say this to Felix",
      blurb:"Drafts a context-aware reply grounded in the matter — and never sends it.",
      detail:"Email Reply pulls the relevant matter context and drafts a reply in the firm's voice. Presenting the draft is the whole job — outgoing mail goes out only when you explicitly say to send it.",
      examples:["Respond to [email]","Draft reply to [client]","Email [client] about [topic]"],
      notes:["A hard rule (and an enforced safeguard): no email is sent without an explicit “send” / “approved” from you."],
      related:["cover-letter","ms365"] },

    /* ---------------- Filings ---------------- */
    { id:"pdf-scan", cat:"filings", kind:"command", name:"PDF Scan",
      trigger:"PDF Scan", command:"PDF Scan", invoke:"Say this to Felix",
      blurb:"Reads the most recent scanned PDFs and extracts deadlines, signatures, action items, dates, and payments.",
      detail:"PDF Scan reads the most recent items in the scans folder and extracts what matters — court deadlines, needed signatures, action items, key dates, payments, and the client/matter it belongs to. Limited to the most recent few to stay focused.",
      examples:["Scan recent PDFs"],
      related:["recorded-deed-filer","ct-court-lookup"] },

    { id:"ct-court-lookup", cat:"filings", kind:"command", name:"CT Court Lookup",
      trigger:"Court lookup [party]", command:"Court lookup [party]", invoke:"Say this to Felix",
      blurb:"Searches the Connecticut judicial case-lookup by party or docket and can download the filings it finds.",
      detail:"CT Court Lookup queries the Connecticut judicial case-lookup by party name or docket number — across case types like foreclosure, probate appeal, and collections — and can download the filings into the matter folder.",
      examples:["Get court filings for [name]","Download [docket]"],
      related:["pdf-scan","turbocourt-download"] },

    { id:"turbocourt-efiling", cat:"filings", kind:"command", name:"TurboCourt eFiling",
      trigger:"File [doc] through TurboCourt", command:"File [doc] through TurboCourt", invoke:"Say this to Felix",
      blurb:"Drives Connecticut probate e-filing end to end — but always stops before final submission and waits for approval.",
      detail:"TurboCourt eFiling navigates the whole probate e-filing flow and prepares the submission — then stops. It presents a filing summary and waits for an explicit “yes” before submitting, because court filings are irreversible.",
      steps:["Opens the case and selects the filing","Uploads the document and fills the e-filing form","Presents a filing summary for review","Submits only on your explicit approval"],
      notes:["A mandatory stop before submit — Felix prepares; you press the button."],
      related:["turbocourt-download","slash-turbocourt-efiling","turbocourt"] },

    { id:"turbocourt-download", cat:"filings", kind:"command", name:"TurboCourt Download",
      trigger:"Download [case] documents", command:"Download [case] documents from TurboCourt", invoke:"Say this to Felix",
      blurb:"Retrieves filed documents and confirmations from TurboCourt into the matter folder.",
      detail:"TurboCourt Download pulls filed documents and confirmation receipts down from TurboCourt and saves them to the matter folder for the record.",
      related:["turbocourt-efiling","turbocourt"] },

    /* ---------------- Research ---------------- */
    { id:"upm-lookup", cat:"research", kind:"command", name:"UPM Lookup",
      trigger:"UPM lookup [topic]", command:"UPM lookup [topic]", invoke:"Say this to Felix",
      blurb:"Researches the Connecticut DSS Uniform Policy Manual for Medicaid rules, always citing section numbers.",
      detail:"UPM Lookup searches the Connecticut DSS Uniform Policy Manual for the rule on a topic, citing section numbers, checking transmittals for amendments, following cross-references, and flagging ambiguity rather than papering over it.",
      examples:["UPM lookup transfer penalty","UPM lookup spousal protections"],
      notes:["A SNAP section is never assumed to apply to Medicaid unless it names Medicaid."],
      related:["fair-hearings","legal-research","ct-medicaid-eligibility","ct-upm"] },

    { id:"fair-hearings", cat:"research", kind:"command", name:"Fair Hearings Lookup",
      trigger:"Fair hearing lookup [topic]", command:"Fair hearing lookup [topic]", invoke:"Say this to Felix",
      blurb:"Searches Connecticut DSS fair-hearing decisions for how an issue has been decided — persuasive, never binding.",
      detail:"Fair Hearings Lookup searches DSS fair-hearing decisions for how an issue has come out. Results are treated as persuasive context only — Felix quotes the actual outcome, checks every policy section the decision cites for later amendments, confirms it's a Medicaid (not SNAP/cash-assistance) decision, and notes distinguishing facts.",
      examples:["Find hearings on [issue]","Has DSS ruled on [issue]?"],
      notes:["Persuasive only — never cited as binding authority."],
      related:["upm-lookup","legal-research","ct-upm"] },

    { id:"legal-research", cat:"research", kind:"command", name:"Statutes, Regulations & Case Law",
      trigger:"Look up [statute / case / regulation]", command:"Look up CGS [section] — or — find CT cases on [issue]", invoke:"Ask Felix",
      blurb:"Searches the full legal-authority database behind the practice — Connecticut statutes, state and federal regulations, federal public laws, CMS guidance, the State Medicaid Manual, and binding CT court decisions.",
      detail:"The UPM and fair hearings are only one corner of what Felix can search. Behind them sits a deep, full-text legal-research database of primary law and binding authority — statutes, regulations, federal law, agency guidance, and court decisions. Ask for a statute, a regulation, a federal rule, or a case on point, and Felix searches the right corpus and cites it by section or docket.",
      contents:[
        {label:"Connecticut General Statutes", desc:"Full text of Title 17b (Social Services & Medicaid), Title 19a (Public Health, nursing homes & home care), and Title 45a (Probate Courts, decedents' estates, conservatorship & trusts). Source: cga.ct.gov."},
        {label:"CT Appellate & Supreme Court decisions", desc:"521 Connecticut appellate and supreme court decisions (2003–present) on Medicaid, conservatorship, elder law, and DSS disputes — binding authority, stronger than a fair-hearing decision."},
        {label:"Regulations of CT State Agencies (RCSA)", desc:"Administrative regulations promulgated by DSS, DPH, and other Connecticut agencies."},
        {label:"Federal regulations (42 CFR)", desc:"The federal Medicaid regulations governing eligibility, coverage, payment, fair hearings, and managed care."},
        {label:"Federal public laws", desc:"Full text of key acts — including the Deficit Reduction Act of 2005, the source of the 5-year look-back, annuity, and home-equity rules."},
        {label:"CMS guidance", desc:"Sub-regulatory guidance: State Medicaid Director letters, State Health Official letters, and Informational Bulletins."},
        {label:"CMS State Medicaid Manual (Pub. 45)", desc:"The federal manual on how states implement Medicaid — the federal complement to the state-level UPM."},
      ],
      examples:["Look up CGS 17b-261","Find CT cases on Medicaid transfer penalties","What does 42 CFR say about fair-hearing timelines?","Search the State Medicaid Manual for annuity rules"],
      notes:["Court decisions are binding authority. The UPM is state policy; fair-hearing decisions are persuasive only — Felix weights them accordingly."],
      related:["upm-lookup","fair-hearings","probate-library","ct-upm"] },

    { id:"probate-library", cat:"research", kind:"command", name:"Probate Reference Library",
      trigger:"Check the Probate Clerk's Manual", command:"Check the Probate Court Clerk's Manual on [topic]", invoke:"Ask Felix",
      blurb:"The Connecticut probate practice library the court-facing skills draw on — the Clerk's Manual, the Rules of Procedure, and the statutory fee schedules.",
      detail:"Apart from the Medicaid materials, Felix keeps the Connecticut probate practice library on hand — the references that govern how the probate courts actually operate — and the probate skills consult it automatically when preparing filings.",
      contents:[
        {label:"Probate Court Clerk's Manual", desc:"The Connecticut Probate Court Clerk's Manual (438 pp., January 2022, 11th edition) — the operational reference for probate practice."},
        {label:"Rules of Procedure", desc:"The Connecticut Probate Court Rules of Procedure governing filings, notice, hearings, and process."},
        {label:"Statutory fee schedules", desc:"The probate fee schedules that back the fee-calculation skill."},
      ],
      examples:["Check the Clerk's Manual on [topic]","What do the Probate Rules say about [issue]?"],
      related:["ct-probate-procedure","fee-calculation","filing-packet","form-filler"] },

    { id:"death-search", cat:"research", kind:"command", name:"Death Search",
      trigger:"Search deaths for [names]", command:"Search deaths for [names]", invoke:"Say this to Felix",
      blurb:"Verifies dates of death — used to confirm will signers and decedents for estate work.",
      detail:"Death Search verifies dates of death for a batch of names — used to confirm decedents and to check will signers. It works through names in batches with a brief pause between each.",
      examples:["Check if deceased: [names]"],
      related:["familysearch","estate-administration"] },

    { id:"deed-acquisition", cat:"research", kind:"command", name:"Deed Acquisition",
      trigger:"Get deed for [address]", command:"Get deed for [address]", invoke:"Say this to Felix",
      blurb:"Retrieves recorded deeds and legal descriptions for Fairfield County properties.",
      detail:"Deed Acquisition pulls the recorded deed and legal description for a property from the town land records — supporting most Fairfield County towns. Legal descriptions are verified character-by-character against the deed image before use.",
      examples:["Property description for [address]"],
      related:["ct-title-clearing"] },

    { id:"roam-todo-sync", cat:"research", kind:"command", name:"Roam TODO Sync",
      trigger:"Sync Roam TODOs", command:"Sync Roam TODOs", invoke:"Say this to Felix",
      blurb:"Pulls open to-dos out of the knowledge base, parses deadline, matter, and priority, and offers to sync each into the task manager.",
      detail:"Roam TODO Sync extracts uncompleted to-dos from recent daily notes, parses each one's deadline, matter, and priority, and asks before syncing each into the task manager — so nothing falls between the knowledge base and the task list.",
      related:["roam","todoist"] },

    /* ---------------- Elder Law Skills ---------------- */
    { id:"ct-medicaid-eligibility", cat:"elderlaw", kind:"skill", name:"CT Medicaid Eligibility",
      trigger:"(applied automatically)", command:"Analyze Medicaid eligibility for [matter]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Asset limits, income rules, transfer penalties, spousal protections, and the policy references behind a Connecticut long-term-care Medicaid analysis.",
      detail:"This skill carries Connecticut's long-term-care Medicaid rules — asset and income limits, the transfer-penalty framework, spousal protections, and the policy-manual references — and applies them automatically whenever a conversation turns to eligibility, spend-down, or a DSS application.",
      examples:["Is [client] eligible for Medicaid?","Run a spend-down analysis for [matter]"],
      related:["slash-medicaid-analysis","upm-lookup","verifications-review","slash-asset-protection"] },

    { id:"ct-probate-procedure", cat:"elderlaw", kind:"skill", name:"CT Probate Procedure",
      trigger:"(applied automatically)", command:"What's the probate procedure for [matter]?", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Filing requirements, forms, timelines, jurisdiction, and court rules under Connecticut Title 45a.",
      detail:"The procedural backbone for Connecticut probate — which form, which court, what deadline, and what rule — applied automatically whenever a matter involves a probate filing, decree, or court appearance.",
      related:["estate-administration","filing-packet","form-filler","ct-probate-procedure"] },

    { id:"estate-administration", cat:"elderlaw", kind:"skill", name:"Estate Administration",
      trigger:"(applied automatically)", command:"Help me administer the [name] estate", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Fiduciary duties, marshaling assets, creditor claims, tax obligations, and distribution in a decedent's estate.",
      detail:"Covers the arc of settling a decedent's estate — the fiduciary's duties, marshaling and valuing assets, the creditor-claim process, tax obligations, and distribution — and applies whenever a conversation involves an executor, administrator, or decedent's estate.",
      related:["estate-accounting","pc237","ct-706nt","slash-estate-timeline"] },

    { id:"estate-accounting", cat:"elderlaw", kind:"skill", name:"Estate Accounting",
      trigger:"(applied automatically)", command:"Prepare an estate accounting for [matter]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Short- and long-form probate accountings with income, gain/loss, and distribution schedules that balance.",
      detail:"The skill behind a probate accounting — fiduciary acquisition values, income schedules, gain/loss on sales, distribution reconciliation, and cash reconciliation — producing short- or long-form accountings whose schedules tie out.",
      related:["slash-estate-accounting","estate-administration"] },

    { id:"elder-law-planning", cat:"elderlaw", kind:"skill", name:"Elder Law Planning",
      trigger:"(applied automatically)", command:"Draft an estate plan for [client]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Powers of attorney, health-care directives, trusts, asset protection, special-needs planning, and Medicaid pre-planning.",
      detail:"The planning skill — powers of attorney, health-care directives, revocable and irrevocable trusts, asset-protection strategy, special-needs planning, and Medicaid pre-planning — applied whenever the work shifts from administering an estate to designing one.",
      related:["slash-asset-protection","document-drafting","ct-medicaid-eligibility"] },

    { id:"conservatorship", cat:"elderlaw", kind:"skill", name:"Conservatorship",
      trigger:"(applied automatically)", command:"Help with the conservatorship of [name]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Voluntary and involuntary conservatorship — incapacity, fiduciary duties, reporting, termination, and alternatives.",
      detail:"Connecticut conservatorship law — voluntary and involuntary proceedings, the incapacity standard, the conservator's duties and reporting obligations, termination, and less-restrictive alternatives — applied to petitions, incapacity questions, and conservator reporting.",
      related:["ct-probate-procedure","filing-packet"] },

    { id:"document-drafting", cat:"elderlaw", kind:"skill", name:"Document Drafting Standards",
      trigger:"(applied automatically)", command:"Draft a [will / POA / deed] for [client]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"The firm's formatting, style, execution, and Connecticut-specific conventions for every document Felix produces.",
      detail:"The firm's drafting standard — formatting, style, execution requirements, and Connecticut conventions for wills, trusts, deeds, powers of attorney, retainers, court filings, and correspondence — applied automatically to anything Felix drafts.",
      notes:["Paper is always US Letter. Client drafts are delivered as PDF, not editable documents."],
      related:["elder-law-planning","cover-letter","legal-templates"] },

    { id:"ct-706nt", cat:"elderlaw", kind:"skill", name:"CT-706 NT Preparation",
      trigger:"(applied automatically)", command:"Prepare the CT-706 NT for the [name] estate", invoke:"Ask Felix — this skill auto-applies",
      blurb:"The Connecticut estate tax return for nontaxable estates — valuation, inclusion rules, and form-year selection.",
      detail:"Prepares the Connecticut estate tax return for nontaxable estates — choosing the right form for the year of death, applying valuation and inclusion rules, filling the official form by field, using whole-dollar formatting, and reconciling to the inventory.",
      related:["estate-administration","pc237","form-filler","fee-calculation"] },

    { id:"pc237", cat:"elderlaw", kind:"skill", name:"PC-237 Return of Claims",
      trigger:"(applied automatically)", command:"Prepare the PC-237 for the [name] estate", invoke:"Ask Felix — this skill auto-applies",
      blurb:"The return of creditor claims and notified-creditor list, including the claims-period deadlines and dispositions.",
      detail:"Prepares the return of creditor claims for an estate — distinguishing claims from administration expenses, recording allow/disallow/compromise dispositions, listing notified creditors, and tracking the claims-period deadline.",
      related:["estate-administration","ct-706nt","filing-packet"] },

    { id:"ct-title-clearing", cat:"elderlaw", kind:"skill", name:"CT Title Clearing",
      trigger:"(applied automatically)", command:"Clear title on [property] after [decedent]'s death", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Clearing Connecticut real-property title after a death — survivorship close-outs, lien releases, and the Tax-Purposes-Only workflow.",
      detail:"Clears Connecticut real-property title after a death — survivorship and life-estate close-outs via the recorded certificate releasing liens, the Tax-Purposes-Only workflow for never-probated decedents, and the Medicaid/DSS lien analysis title companies ask about.",
      related:["deed-acquisition","estate-administration"] },

    { id:"form-filler", cat:"elderlaw", kind:"skill", name:"CT Probate Form Filler",
      trigger:"(applied automatically)", command:"Fill out the [PC-form number] for [matter]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"A universal engine that can fetch, map, fill, and verify any of the roughly 195 official Connecticut probate (PC) forms.",
      detail:"A universal engine for any probate (PC) form that doesn't have its own dedicated skill — it fetches the current official blank, reads its fillable fields, builds and visually verifies a field map, fills from grounded case data, and render-verifies the result.",
      examples:["Prepare a PC-181 waiver","Complete the inventory PC-2407"],
      related:["filing-packet","ct-probate-procedure"] },

    { id:"filing-packet", cat:"elderlaw", kind:"skill", name:"Probate Filing Packet",
      trigger:"(applied automatically)", command:"Assemble the [opening / inventory / closing] packet for [matter]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Assembles a complete, internally consistent set of forms for a matter from one grounded fact set.",
      detail:"Assembles a complete filing packet for a matter — estate opening, small-estate, inventory, return of claims, closing, conservatorship petitions and accounts, or title clearing — with every form prefilled from the same grounded facts, plus a checklist of conditional items and a cross-form consistency check.",
      examples:["Open the estate for [matter]","What do we need to file for [matter]?"],
      related:["form-filler","ct-probate-procedure","slash-ct-probate-filing"] },

    { id:"verifications-review", cat:"elderlaw", kind:"skill", name:"Medicaid Verifications Review",
      trigger:"(applied automatically)", command:"Review the verifications for [applicant]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"A repeatable review of an applicant's bank and brokerage statements — large transactions, account discovery, reconciliation, and a clean schedule.",
      detail:"A repeatable review of a Medicaid applicant's financial statements — flagging every deposit or withdrawal at or above the reporting threshold, sweeping for references to accounts that haven't been submitted (including ones closed during the lookback), reconciling each statement by running balance, and producing a clean transaction schedule.",
      examples:["Find the $5,000+ transactions for [applicant]","Are there any other accounts for [applicant]?"],
      related:["slash-verifications-review","ct-medicaid-eligibility"] },

    { id:"fee-calculation", cat:"elderlaw", kind:"skill", name:"CT Probate Fee Calculation",
      trigger:"(applied automatically)", command:"Calculate the probate fee for the [name] estate", invoke:"Ask Felix — this skill auto-applies",
      blurb:"The statutory probate fee under Connecticut law, including the fee basis, the correct date-of-death table, exemptions, and interest.",
      detail:"Computes the Connecticut statutory probate fee — determining the fee basis (the greatest of inventory, taxable estate, or gross estate, with spousal-share and out-of-state reductions), selecting the date-of-death fee table, applying exemptions, and computing any interest on the unpaid fee.",
      examples:["What will the court charge on the [name] estate?"],
      related:["ct-706nt","estate-administration"] },

    { id:"bus039", cat:"elderlaw", kind:"skill", name:"BUS-039 LLC → Trust Transfer",
      trigger:"(applied automatically)", command:"Transfer the [LLC] interest into the [trust]", invoke:"Ask Felix — this skill auto-applies",
      blurb:"Transferring an LLC membership interest into a revocable trust — the state interim-notice form plus the assignment documents.",
      detail:"Handles transferring an LLC membership interest into a revocable trust — preparing the state's interim notice of change of member/manager and the accompanying assignment(s) of membership interest, including the case where an interest passes through a decedent's estate.",
      related:["elder-law-planning","document-drafting"] },

    /* ---------------- Slash commands ---------------- */
    { id:"slash-medicaid-analysis", cat:"slash", kind:"skill", name:"/elder-law:medicaid-analysis",
      trigger:"/elder-law:medicaid-analysis", command:"/elder-law:medicaid-analysis", invoke:"Slash command",
      blurb:"A guided Medicaid eligibility analysis — asset review, income calculation, transfer-penalty exposure, and planning options.",
      detail:"A step-by-step interactive workflow that walks a full Medicaid eligibility analysis — reviewing assets, calculating income, sizing transfer-penalty exposure, and laying out planning options.",
      related:["ct-medicaid-eligibility","slash-asset-protection","slash-verifications-review"] },

    { id:"slash-estate-timeline", cat:"slash", kind:"skill", name:"/elder-law:estate-timeline",
      trigger:"/elder-law:estate-timeline", command:"/elder-law:estate-timeline", invoke:"Slash command",
      blurb:"Generates a deadline timeline for an active estate, conservatorship, or planning matter.",
      detail:"Generates a forward-looking deadline timeline for a matter — the filings, returns, and reviews due, in order, so nothing is missed.",
      related:["estate-administration","deadlines"] },

    { id:"slash-hearing-prep", cat:"slash", kind:"skill", name:"/elder-law:hearing-prep",
      trigger:"/elder-law:hearing-prep", command:"/elder-law:hearing-prep", invoke:"Slash command",
      blurb:"Prepares for a probate hearing — case summary, evidence checklist, argument outline, and witness prep.",
      detail:"A guided preparation for a probate hearing — building a case summary, an evidence checklist, an argument outline, and witness preparation.",
      related:["ct-probate-procedure","conservatorship"] },

    { id:"slash-asset-protection", cat:"slash", kind:"skill", name:"/elder-law:asset-protection-plan",
      trigger:"/elder-law:asset-protection-plan", command:"/elder-law:asset-protection-plan", invoke:"Slash command",
      blurb:"Develops an asset-protection and Medicaid pre-planning strategy for a client.",
      detail:"Develops an asset-protection and Medicaid pre-planning strategy — weighing tools and timing against the client's situation and goals.",
      related:["elder-law-planning","ct-medicaid-eligibility","slash-medicaid-analysis"] },

    { id:"slash-case-intake", cat:"slash", kind:"skill", name:"/elder-law:case-intake",
      trigger:"/elder-law:case-intake", command:"/elder-law:case-intake", invoke:"Slash command",
      blurb:"Guided intake for a new elder-law matter — gathering facts, spotting issues, and setting the matter up.",
      detail:"A guided intake for a new matter — gathering the facts, identifying the legal issues, and setting up the matter. A conflict check runs before any privileged questions.",
      related:["new-case","slash-conflict-check"] },

    { id:"slash-ct-probate-filing", cat:"slash", kind:"skill", name:"/elder-law:ct-probate-filing",
      trigger:"/elder-law:ct-probate-filing", command:"/elder-law:ct-probate-filing", invoke:"Slash command",
      blurb:"Guides a probate filing — identifying the required forms, preparing them, and filing through TurboCourt.",
      detail:"Guides a probate filing from start to finish — identifying which forms are required, preparing them from grounded data, and filing through TurboCourt (stopping for approval before submission).",
      related:["filing-packet","turbocourt-efiling","slash-turbocourt-efiling"] },

    { id:"slash-estate-accounting", cat:"slash", kind:"skill", name:"/elder-law:estate-accounting",
      trigger:"/elder-law:estate-accounting", command:"/elder-law:estate-accounting", invoke:"Slash command",
      blurb:"Prepares a probate estate accounting with its supporting schedules as a finished document.",
      detail:"Walks the preparation of a probate estate accounting — gathering data, making the accounting decisions, and generating the finished document with its supporting schedules.",
      related:["estate-accounting","estate-administration"] },

    { id:"slash-verifications-review", cat:"slash", kind:"skill", name:"/elder-law:verifications-review",
      trigger:"/elder-law:verifications-review", command:"/elder-law:verifications-review", invoke:"Slash command",
      blurb:"Runs the Medicaid bank-statement verification review as a step-by-step procedure.",
      detail:"Runs the Medicaid financial-verification review as a guided procedure — large transactions, account discovery, reconciliation, packet integrity, and a clean schedule.",
      related:["verifications-review","ct-medicaid-eligibility"] },

    { id:"slash-conflict-check", cat:"slash", kind:"skill", name:"/elder-law:conflict-check",
      trigger:"/elder-law:conflict-check", command:"/elder-law:conflict-check", invoke:"Slash command",
      blurb:"Runs a full conflict check across clients, matters, named parties, and the email archive.",
      detail:"Runs a full conflict check before taking on a matter or a new third party — across clients and matters, named parties in the case database, and the historical email archive — surfacing every prior touchpoint.",
      related:["conflict-check","new-case","slash-case-intake"] },

    { id:"slash-turbocourt-efiling", cat:"slash", kind:"skill", name:"/elder-law:turbocourt-efiling",
      trigger:"/elder-law:turbocourt-efiling", command:"/elder-law:turbocourt-efiling", invoke:"Slash command",
      blurb:"Files probate documents electronically through TurboCourt, stopping for approval before submission.",
      detail:"A guided TurboCourt e-filing workflow — preparing and uploading the documents and stopping at a mandatory review before the irreversible submit step.",
      related:["turbocourt-efiling","slash-ct-probate-filing"] },

    /* ---------------- Automation ---------------- */
    { id:"felix-monitor", cat:"automation", kind:"automation", name:"Felix Inbox Monitor",
      trigger:"(runs 24/7)", command:"Check Felix monitor", invoke:"Runs automatically · check status with",
      blurb:"Polls the Felix inbox around the clock, triages actionable email into tasks, and sends a morning summary.",
      detail:"A round-the-clock daemon that polls the Felix inbox every few minutes, triages actionable email into tasks, and sends a daily summary each morning. Court and firm senders are protected from noise filtering. It also powers the staff-reminder and publication-notice automations.",
      examples:["Felix inbox status"],
      related:["staff-reminder","publication-notice","felix-status"] },

    { id:"staff-reminder", cat:"automation", kind:"automation", name:"Staff Reminder Auto-Handler",
      trigger:"(runs on incoming mail)", command:"Check Felix monitor", invoke:"Runs automatically · inspect with",
      blurb:"Detects reminder emails from staff, matches them to the right project, and creates the task at the right priority.",
      detail:"When a staff member emails a reminder, this detects it, matches it to the right matter or project, creates the task at the appropriate priority and due date, and replies to confirm what it did — so a reminder becomes a tracked task without manual entry.",
      related:["felix-monitor","todoist"] },

    { id:"publication-notice", cat:"automation", kind:"automation", name:"Publication Notice Automation",
      trigger:"(runs on incoming mail)", command:"Process publication notices", invoke:"Runs automatically · drain queue with",
      blurb:"Processes probate publication-notice confirmations and tracks the creditor-claim deadline they trigger.",
      detail:"Detects probate publication-notice emails, processes the confirmation, and tracks the creditor-claim deadline that the actual publication date sets running — pulling that date from the confirmation document rather than the email date.",
      notes:["The email date is not the publication date — the latter drives the claims deadline and is read from the confirmation document."],
      related:["felix-monitor","pc237"] },

    { id:"recorded-deed-filer", cat:"automation", kind:"automation", name:"Recorded Deed Filer",
      trigger:"(runs daily)", command:"Felix status", invoke:"Runs automatically · check with",
      blurb:"Watches for recorded land instruments coming back from town clerks and copies each into the matching matter folder.",
      detail:"A daily daemon that watches the scans folder for recorded land instruments returning from town clerks — deeds, lien releases, mortgage releases — and copies each into the matching matter folder. High-confidence matches file automatically; anything ambiguous becomes a task for review rather than a guess.",
      notes:["Copies, never moves. Ambiguous matches are queued for review — Felix won't guess the matter."],
      related:["pdf-scan","ct-title-clearing","felix-status"] },

    { id:"felix-status", cat:"automation", kind:"command", name:"Felix Status",
      trigger:"Felix status", command:"Felix status", invoke:"Say this to Felix",
      blurb:"A one-screen health dashboard — daemon status, queue depths, database counts, and recent activity.",
      detail:"Felix Status is a single read-only screen of system health — which daemons are running, how deep the queues are, database counts, recent conflict-check dispositions, and recent activity. Instant, and it changes nothing.",
      examples:["System status","Status dashboard"],
      related:["felix-monitor","recorded-deed-filer"] },

    /* ---------------- Integrations ---------------- */
    { id:"ms365", cat:"integrations", kind:"integration", name:"Microsoft 365",
      trigger:"(email & calendar)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Reads and drafts email and manages calendar events — with a hard rule that nothing is sent without approval.",
      detail:"The firm's email and calendar. Felix reads and searches mail, drafts replies, and manages events — but a hard, enforced rule keeps it from sending anything without your explicit approval.",
      examples:["Reply to [client] email","Email [client] about [topic]"],
      related:["email-reply","felix-monitor"] },

    { id:"roam", cat:"integrations", kind:"integration", name:"Roam Research",
      trigger:"(knowledge base)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"The practice's knowledge base — daily notes, memos-to-file, and to-dos.",
      detail:"The practice's knowledge base. Felix writes memos-to-file and daily notes here and reads back prior context, following firm conventions for dates and structure.",
      related:["plaud-sync","roam-todo-sync"] },

    { id:"harvest", cat:"integrations", kind:"integration", name:"Harvest",
      trigger:"(billing)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Time tracking and billing — client lookup, time entries, invoices, and expenses.",
      detail:"The billing system. Felix searches clients and matters, creates time entries at the firm's rate and increment, and works with invoices and expenses.",
      examples:["Bill today","Lookup [client]"],
      related:["bill","scan-billing","client-lookup"] },

    { id:"todoist", cat:"integrations", kind:"integration", name:"Todoist",
      trigger:"(tasks)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Task and deadline management, organized by matter and priority.",
      detail:"The task manager. Felix creates and moves tasks by matter and priority, and reads due tasks for Check In and Deadlines.",
      related:["deadlines","roam-todo-sync","staff-reminder"] },

    { id:"icloud-calendar", cat:"integrations", kind:"integration", name:"iCloud Calendar",
      trigger:"(scheduling)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Appointments, court dates, and the due-dates calendar that drives deadline tracking.",
      detail:"Scheduling. Felix reads appointments and court dates and the dedicated due-dates calendar, and can create events following the firm's scheduling preferences.",
      related:["deadlines","check-in"] },

    { id:"zoom", cat:"integrations", kind:"integration", name:"Zoom",
      trigger:"(meetings & phone)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Creating video meetings, placing phone calls, and pulling call logs and recordings.",
      detail:"Video and phone. Felix can create meetings, place calls through the phone app, and pull call logs and recordings.",
      examples:["Create Zoom meeting","Call [name]"],
      related:["mac-contacts"] },

    { id:"mac-contacts", cat:"integrations", kind:"integration", name:"Mac Contacts",
      trigger:"(contact info)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Names, numbers, and addresses — the lookup behind email and call composition.",
      detail:"The contact directory. Felix resolves names to phone numbers, email addresses, and mailing addresses — the lookup that sits behind composing an email or placing a call.",
      related:["zoom","client-lookup"] },

    { id:"turbocourt", cat:"integrations", kind:"integration", name:"TurboCourt",
      trigger:"(probate e-filing)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Connecticut probate court e-filing and document retrieval automation.",
      detail:"The Connecticut probate e-filing portal. Felix drives filing and document retrieval here — always stopping for approval before an irreversible submission.",
      related:["turbocourt-efiling","turbocourt-download"] },

    { id:"mailsteward", cat:"integrations", kind:"integration", name:"MailSteward",
      trigger:"(email archive)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"The historical email archive going back decades — searched for client history and conflict checks.",
      detail:"The deep email archive. Felix searches it for a client's full history and as part of every conflict check, reaching back far further than the live inbox.",
      related:["conflict-check","client-lookup"] },

    { id:"ct-upm", cat:"integrations", kind:"integration", name:"Connecticut Legal Research Database",
      trigger:"(law, policy & cases)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"A searchable corpus of Connecticut and federal authority — statutes, regulations, 42 CFR, public laws, CMS guidance, the State Medicaid Manual, the DSS Uniform Policy Manual, and binding CT court decisions.",
      detail:"The legal-research backbone. Felix searches a deep, full-text database spanning Connecticut statutes and regulations, federal Medicaid law (42 CFR and key public laws), CMS guidance and the State Medicaid Manual, the DSS Uniform Policy Manual, and Connecticut appellate and supreme court decisions — the source behind every research command in this guide.",
      related:["legal-research","upm-lookup","fair-hearings","ct-medicaid-eligibility"] },

    { id:"familysearch", cat:"integrations", kind:"integration", name:"FamilySearch",
      trigger:"(records)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Death-record and genealogy verification for estate and will-signer work.",
      detail:"Records research. Felix uses it to verify deaths and family relationships — confirming decedents and will signers for estate work.",
      related:["death-search","estate-administration"] },

    { id:"plaud-omi", cat:"integrations", kind:"integration", name:"Plaud & Omi",
      trigger:"(transcription)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Voice and ambient transcription — the source material for memos-to-file.",
      detail:"The transcription services behind the recordings pipeline — voice recordings and ambient desktop capture that become memos-to-file.",
      related:["plaud-sync","omi-desktop-sync","sweep"] },

    { id:"legal-templates", cat:"integrations", kind:"integration", name:"Legal Templates",
      trigger:"(document generation)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"The firm's template library and document-generation engine for letters, retainers, deeds, and memos.",
      detail:"The firm's template and document-generation engine — letters, retainers, deeds, and memos produced to firm formatting standards.",
      related:["document-drafting","cover-letter"] },

    { id:"pdf-forms", cat:"integrations", kind:"integration", name:"PDF Forms",
      trigger:"(form filling)", command:null, invoke:"Felix uses this automatically — no command to launch",
      blurb:"Programmatic filling of fillable PDF forms, with field mapping and render verification.",
      detail:"The form-filling engine — it maps a form's fillable fields, fills them from grounded data, and verifies the result by rendering the finished page. The machinery behind the probate form filler.",
      related:["form-filler","ct-706nt"] },
  ]
};
